[workspace]
members = [
  "crates/font-analysis",
  "crates/js-analysis",
  "crates/sis-pdf-core",
  "crates/sis-pdf-pdf",
  "crates/sis-pdf-detectors",
  "crates/sis-pdf-ml-graph",
  "crates/sis-pdf",
  "tools/cve-update",
]
exclude = [
  "fuzz",
]
resolver = "2"
