[package]
name = "ysnp-detectors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
hex = "0.4"
sha2 = "0.10"
ysnp-core = { path = "../ysnp-core" }
ysnp-pdf = { path = "../ysnp-pdf" }
boa_parser = { version = "0.17", optional = true }

[features]
js-ast = ["boa_parser"]
