[package]
name = "cve-update"
version.workspace = true
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
chrono = "0.4"
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
