[package]
name = "cve-update"
version.workspace = true
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
chrono = "0.4"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
